modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Bennyboy1695/BobberDetector/issues"
license = "MIT"

[[mods]]
modId = "bobberdetector"
version = "${version}"
displayName = "Bobber Detector"
updateJSONURL = "https://raw.githubusercontent.com/Bennyboy1695/BobberDetector/refs/heads/multiloader/update.json"
authors = "GLaD0S, Bennyboy1695"
description = '''
Automatic fishing with create.
'''
#logoFile = ""

[[dependencies.bobberdetector]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bobberdetector]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

