name: Build, Version, and Publish Mod

on:
  push:
    tags:
      - 'v*.*.*'
      - 'test-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Get version from tag
        id: versioning
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Check if test build
        id: testcheck
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/test-* ]]; then
            echo "IS_TEST=true" >> $GITHUB_ENV
          else
            echo "IS_TEST=false" >> $GITHUB_ENV
          fi

      - name: Check enabled loaders
        run: |
          if [[ "${{ secrets.ENABLED_LOADERS }}" == *"forge"* ]]; then
            echo "PUBLISH_FORGE=true" >> $GITHUB_ENV
          else
            echo "PUBLISH_FORGE=false" >> $GITHUB_ENV
          fi
          if [[ "${{ secrets.ENABLED_LOADERS }}" == *"fabric"* ]]; then
            echo "PUBLISH_FABRIC=true" >> $GITHUB_ENV
          else
            echo "PUBLISH_FABRIC=false" >> $GITHUB_ENV
          fi

      # Conditionally build Forge
      - name: Build Forge
        if: ${{ env.PUBLISH_FORGE == 'true' }}
        run: ./gradlew :forge:build -Pversion=${{ env.VERSION }}

      # Conditionally build Fabric
      - name: Build Fabric
        if: ${{ env.PUBLISH_FABRIC == 'true' }}
        run: ./gradlew :fabric:build -Pversion=${{ env.VERSION }}

      - name: Generate changelog
        id: changelog
        run: |
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0)..HEAD >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Publish Forge
        uses: Kira-NT/mc-publish@v3.3
        if: ${{ env.IS_TEST != 'true' && env.PUBLISH_FORGE == 'true' }}
        with:
            modrinth-id: GRznXwf3
            modrinth-featured: true
            curseforge-id: 897858
            loaders: |
              forge
              neoforge
            game-versions: |
              1.20.1
            version: ${{ env.VERSION }}
            changelog: ${{ env.CHANGELOG }}
            files: forge/build/libs/*.jar:forge
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Fabric
        if: ${{ env.IS_TEST != 'true' && env.PUBLISH_FABRIC == 'true' }}
        uses: Kira-NT/mc-publish@v3
        with:
          modrinth-id: GRznXwf3
          modrinth-featured: true
          curseforge-id: 897858
          loaders: |
            fabric
          game-versions: |
              1.20.1
          version: ${{ env.VERSION }}
          changelog: ${{ env.CHANGELOG }}
          files: fabric/build/libs/*.jar:fabric
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
